### ISSUE TITLE
Build error against PostgreSQL 13

### ISSUE THREAD

**Issue by devrimgunduz** [HighgoSoftware/wal2mongo#1]
Hi,

1.0.6 fails to build against PostgreSQL 13. 13.0 is due tomorrow. Can you please take a look?

wal2mongo.c:26:10: fatal error: utils/jsonapi.h: No such file or directory
   26 | #include "utils/jsonapi.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: wal2mongo.o] Error 1
make[1]: *** Waiting for unfinished jobs....
wal2mongo.c:26:10: fatal error: 'utils/jsonapi.h' file not found
#include "utils/jsonapi.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.

Regards, Devrim

**Comment by devrimgunduz** [comment]
Hi,

Any updates?

Regards, Devrim

**Comment by devrimgunduz-edb** [comment]
ping.

**Comment by devrimgunduz-edb** [comment]
ping

**Comment by tanhv90** [comment]
@devrimgunduz @devrimgunduz-edb 
Please see my pull request here. It supports for Postgres 13
https://github.com/HighgoSoftware/wal2mongo/pull/3

**Comment by idrawone** [comment]
sorry for the late! the build issues has been fixed and verified not only on PostgreSQL 13, 14 but also 15 and 16. please see the [latest release v1.0.7](https://github.com/HighgoSoftware/wal2mongo/releases/tag/v1.0.7).

**Comment by idrawone** [comment]
sorry for the late! the build issues has been fixed and verified not only on PostgreSQL 13, 14 but also 15 and 16. please see the [latest release v1.0.7](https://github.com/HighgoSoftware/wal2mongo/releases/tag/v1.0.7).
