### ISSUE TITLE
Build error against PostgreSQL 14

### ISSUE THREAD

**Issue by devrimgunduz** [HighgoSoftware/wal2mongo#2]
Hi,

1.0.6 fails to build against PostgreSQL 14. v14 beta1 is already out. Can you please take a look?

wal2mongo.c:26:10: fatal error: utils/jsonapi.h: No such file or directory
26 | #include "utils/jsonapi.h"
| ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [: wal2mongo.o] Error 1
make[1]: *** Waiting for unfinished jobs....
wal2mongo.c:26:10: fatal error: 'utils/jsonapi.h' file not found
#include "utils/jsonapi.h"
^~~~~~~~~~~~~~~~~
1 error generated.

Regards, Devrim

**Comment by devrimgunduz** [comment]
ping

**Comment by tanhv90** [comment]
@devrimgunduz 
See my pull request https://github.com/HighgoSoftware/wal2mongo/pull/3

**Comment by devrimgunduz** [comment]
@tanhv90 thnaks,. Who's committing it?

**Comment by devrimgunduz** [comment]
@idrawone ping. v14 is around the corner.

**Comment by devrimgunduz** [comment]
ping.

**Comment by devrimgunduz** [comment]
ping.

**Comment by tanhv90** [comment]
> @tanhv90 thnaks,. Who's committing it?

I am. Have you tried it?

**Comment by devrimgunduz** [comment]
We need a tarball (release) please to test.

**Comment by idrawone** [comment]
> We need a tarball (release) please to test.

We are planing to update for latest Postgres builds in coming days.

**Comment by idrawone** [comment]
sorry for the late! the build issues has been fixed and verified not only on PostgreSQL 13, 14 but also 15 and 16. please see the [latest release v1.0.7](https://github.com/HighgoSoftware/wal2mongo/releases/tag/v1.0.7).

**Comment by idrawone** [comment]
sorry for the late! the build issues has been fixed and verified not only on PostgreSQL 13, 14 but also 15 and 16. please see the [latest release v1.0.7](https://github.com/HighgoSoftware/wal2mongo/releases/tag/v1.0.7).

**Comment by idrawone** [comment]
sorry for the late! the build issues has been fixed and verified not only on PostgreSQL 13, 14 but also 15 and 16. please see the [latest release v1.0.7](https://github.com/HighgoSoftware/wal2mongo/releases/tag/v1.0.7).
